package Vistas;

import entidades.Alumno;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class AlumnosInscriptos extends javax.swing.JInternalFrame {
    public AlumnosInscriptos() {
        super("ALUMNOS INSCRIPTOS");
        initComponents();
        cargaAlumnos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTDatos = new javax.swing.JTable();
        jBSalir = new javax.swing.JButton();
        jBBorrar = new javax.swing.JButton();

        jTDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTDatos.setShowGrid(false);
        jScrollPane1.setViewportView(jTDatos);

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jBBorrar.setText("Borrar");
        jBBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBBorrar)
                        .addGap(18, 18, 18)
                        .addComponent(jBSalir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalir)
                    .addComponent(jBBorrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarActionPerformed
        DefaultTableModel model=(DefaultTableModel) jTDatos.getModel();
        int[] selec=jTDatos.getSelectedRows();
        Object[] id=new Object[selec.length];
        for (int i = 0; i < selec.length; i++) {
            id[i]=(String) model.getValueAt(selec[i], 0);
        }
        if(id.length>0){
            for (int i = 0; i < id.length; i++) {
                InscripcionAlumnos.alumD.eliminarAlumno(Integer.parseInt((String) id[i]));
            }
            cargaAlumnos();
        }
    }//GEN-LAST:event_jBBorrarActionPerformed

    private void cargaAlumnos(){
        String colum[]={"ID","Apellido","Nombre","DNI","Fecha Nacimiento"};
        InscripcionAlumnos.alumnos=InscripcionAlumnos.alumD.alumnosInscriptos();
        String datos[][]=new String[InscripcionAlumnos.alumnos.size()][5];
        int i=0;
        for (Alumno alum : InscripcionAlumnos.alumnos) {
            datos[i][0]= alum.getIdAlumno()+"";
            datos[i][1]=alum.getApellido();
            datos[i][2]=alum.getNombre();
            datos[i][3]=alum.getDni()+"";
            datos[i][4]=alum.getFechaNacimiento().getDayOfMonth()+"/"+alum.getFechaNacimiento().getMonth().getValue()+"/"+alum.getFechaNacimiento().getYear();
            i++;
            alum=null;
        }
        jTDatos.setModel(new DefaultTableModel(datos,colum));
        InscripcionAlumnos.alumnos=null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBorrar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTDatos;
    // End of variables declaration//GEN-END:variables
}
