package Vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class BuscarAlumno extends javax.swing.JInternalFrame {

    public BuscarAlumno() {
        super("Buscar Alumno");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botones = new javax.swing.ButtonGroup();
        jRBID = new javax.swing.JRadioButton();
        jRBDNI = new javax.swing.JRadioButton();
        jTDNI = new javax.swing.JTextField();
        jTNombre = new javax.swing.JTextField();
        jTID = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jLNombre = new javax.swing.JLabel();
        jTApellido = new javax.swing.JTextField();
        jLApellido = new javax.swing.JLabel();
        jTNacimiento = new javax.swing.JTextField();
        jLNacimiento = new javax.swing.JLabel();
        jBEliminar = new javax.swing.JButton();

        Botones.add(jRBID);
        jRBID.setText("ID");
        jRBID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBIDActionPerformed(evt);
            }
        });

        Botones.add(jRBDNI);
        jRBDNI.setText("DNI");
        jRBDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBDNIActionPerformed(evt);
            }
        });

        jTDNI.setEditable(false);
        jTDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTDNIKeyTyped(evt);
            }
        });

        jTNombre.setEditable(false);

        jTID.setEditable(false);
        jTID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTIDKeyTyped(evt);
            }
        });

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        jLNombre.setText("Nombre");

        jTApellido.setEditable(false);

        jLApellido.setText("Apellido");

        jTNacimiento.setEditable(false);

        jLNacimiento.setText("Nacimiento");

        jBEliminar.setText("Eliminar");
        jBEliminar.setEnabled(false);
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBDNI)
                            .addComponent(jRBID)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLNombre)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBEliminar)
                            .addGap(18, 18, 18)
                            .addComponent(jBBuscar)
                            .addGap(18, 18, 18)
                            .addComponent(jBLimpiar)
                            .addGap(18, 18, 18)
                            .addComponent(jBSalir))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(jLApellido))
                                .addComponent(jLNacimiento))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(jTApellido)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRBID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTNombre)
                    .addComponent(jLNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTApellido)
                    .addComponent(jLApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTNacimiento)
                    .addComponent(jLNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalir)
                    .addComponent(jBBuscar)
                    .addComponent(jBLimpiar)
                    .addComponent(jBEliminar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        Limpiar();
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jRBIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBIDActionPerformed
        jTID.setEditable(true);
        jTDNI.setEditable(false);
        Limpiar();
    }//GEN-LAST:event_jRBIDActionPerformed

    private void jRBDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBDNIActionPerformed
        jTID.setEditable(false);
        jTDNI.setEditable(true);
        Limpiar();
    }//GEN-LAST:event_jRBDNIActionPerformed

    ///--------------BOTON BUSCAR--------------
    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        boolean msj=false;
        verificarSelector();
        if(jRBID.isSelected()){
            msj=verificarCampos(jTID);
            if(!msj){
                InscripcionAlumnos.alum=InscripcionAlumnos.alumD.buscarAlumno(Integer.parseInt(jTID.getText()));
            }
        }else if(jRBDNI.isSelected()){
            msj=verificarCampos(jTDNI);
            if(!msj){
                InscripcionAlumnos.alum=InscripcionAlumnos.alumD.buscarAlumnoPorDNI(Integer.parseInt(jTDNI.getText()));
            }
        }
        if(InscripcionAlumnos.alum!=null && !msj){
            jBEliminar.setEnabled(true);
            jTID.setText(InscripcionAlumnos.alum.getIdAlumno()+"");
            jTDNI.setText(InscripcionAlumnos.alum.getDni()+"");
            jTApellido.setText(InscripcionAlumnos.alum.getApellido());
            jTNombre.setText(InscripcionAlumnos.alum.getNombre());
            jTNacimiento.setText(InscripcionAlumnos.alum.getFechaNacimiento().getDayOfMonth()+"/"+InscripcionAlumnos.alum.getFechaNacimiento().getMonth().getValue()+"/"+InscripcionAlumnos.alum.getFechaNacimiento().getYear());
        }else if((jRBID.isSelected()||jRBDNI.isSelected())&&!msj){
            JOptionPane.showMessageDialog(null, "Alumno no encontrado");
            Limpiar();
        }
        InscripcionAlumnos.alum=null;
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jTIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTIDKeyTyped
        if(jTID.isEditable()){
            verificarSoloNumeros(evt,jTID);
        }
    }//GEN-LAST:event_jTIDKeyTyped

    ///--------------BOTON ELIMINAR--------------
    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        verificarSelector();
        if(jRBID.isSelected()){
            eliminar();
        }else if(jRBDNI.isSelected()){
            eliminar();
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jTDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDNIKeyTyped
        if(jTDNI.isEditable()){
            verificarSoloNumeros(evt,jTDNI);
        }
    }//GEN-LAST:event_jTDNIKeyTyped

    private void eliminar(){
        if(!verificarCampos(jTID)){
            InscripcionAlumnos.alumD.eliminarAlumno(Integer.parseInt(jTID.getText()));
            Limpiar();
        }
    }
    
    private void verificarSelector(){
        if(!jRBID.isSelected()&&!jRBDNI.isSelected()){
            JOptionPane.showMessageDialog(null, "Elija una opcion");
        }
    }
    
    private boolean verificarCampos(javax.swing.JTextField tx){
        if(tx.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Completar Campo");
            tx.requestFocus();
            return true;
        }else{return false;}
    }
    
    private void Limpiar(){
        jTID.setText("");
        jTDNI.setText("");
        jTNombre.setText("");
        jTApellido.setText("");
        jTNacimiento.setText("");
        jBEliminar.setEnabled(false);
    }

    private void verificarSoloNumeros(java.awt.event.KeyEvent evt,javax.swing.JTextField tx){
        if((evt.getKeyChar()<48||evt.getKeyChar()>57)&&evt.getKeyChar()!=8){
            JOptionPane.showMessageDialog(this, "Igresar solo numeros","Advertencia",JOptionPane.WARNING_MESSAGE);
            evt.consume();
            tx.requestFocus();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Botones;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLNacimiento;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JRadioButton jRBDNI;
    private javax.swing.JRadioButton jRBID;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTDNI;
    private javax.swing.JTextField jTID;
    private javax.swing.JTextField jTNacimiento;
    private javax.swing.JTextField jTNombre;
    // End of variables declaration//GEN-END:variables
}
