/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import accesoADatos.AlumnoData;
import accesoADatos.InscripcionData;
import accesoADatos.MateriaData;
import entidades.Alumno;
import entidades.Inscripcion;
import entidades.Materia;
import java.util.List;

/**
 *
 * @author 54265
 */
public class InscripcionAlumnos extends javax.swing.JFrame {
    public static InscripcionData inscripD=new InscripcionData();
    public static AlumnoData alumD=new AlumnoData();
    public static MateriaData matD=new MateriaData();
    public static Alumno alum=null;
    public static Materia mat=null;
    public static Inscripcion inscrip=null;
    public static List<Alumno> alumnos=null;
    public static List<Materia> materias=null;
    public static List<Inscripcion> inscripciones=null;
    /**
     * Creates new form InscripcionAlumnos
     */
    public InscripcionAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMArchivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMMaterias = new javax.swing.JMenu();
        jMenuMaterias = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMInscripciones = new javax.swing.JMenu();
        jMIMaterias = new javax.swing.JMenuItem();
        jMCargadeNotas = new javax.swing.JMenu();
        jMConsultas = new javax.swing.JMenu();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        org.jdesktop.layout.GroupLayout jEscritorioLayout = new org.jdesktop.layout.GroupLayout(jEscritorio);
        jEscritorio.setLayout(jEscritorioLayout);
        jEscritorioLayout.setHorizontalGroup(
            jEscritorioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 438, Short.MAX_VALUE)
        );
        jEscritorioLayout.setVerticalGroup(
            jEscritorioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 279, Short.MAX_VALUE)
        );

        jMArchivo.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMArchivo.add(jMenuItem1);

        jMenuBar1.add(jMArchivo);

        jMMaterias.setText("Materias");

        jMenuMaterias.setText("Formulario de Materias");
        jMenuMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMateriasActionPerformed(evt);
            }
        });
        jMMaterias.add(jMenuMaterias);

        jMenuBar1.add(jMMaterias);

        jMenu3.setText("Alumno");

        jMenuItem3.setText("Formulario de Alumnos");
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMInscripciones.setText("Inscripciones");

        jMIMaterias.setText("Materias");
        jMIMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIMateriasActionPerformed(evt);
            }
        });
        jMInscripciones.add(jMIMaterias);

        jMenuBar1.add(jMInscripciones);

        jMCargadeNotas.setText("Carga de Notas");
        jMenuBar1.add(jMCargadeNotas);

        jMConsultas.setText("Consultas");
        jMenuBar1.add(jMConsultas);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMateriasActionPerformed
        // TODO add your handling code here:
        jEscritorio.removeAll();
        jEscritorio.repaint();
        viewMaterias cM=new viewMaterias();
        cM.setVisible(true);
        jEscritorio.add(cM);
    }//GEN-LAST:event_jMenuMateriasActionPerformed

    private void jMIMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIMateriasActionPerformed
        jEscritorio.removeAll();
        jEscritorio.repaint();
        viewFormulariodeInscripcion vFI=new viewFormulariodeInscripcion();
        vFI.setVisible(true);
        jEscritorio.add(vFI);
    }//GEN-LAST:event_jMIMateriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InscripcionAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InscripcionAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InscripcionAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InscripcionAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InscripcionAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jEscritorio;
    private javax.swing.JMenu jMArchivo;
    private javax.swing.JMenu jMCargadeNotas;
    private javax.swing.JMenu jMConsultas;
    private javax.swing.JMenuItem jMIMaterias;
    private javax.swing.JMenu jMInscripciones;
    private javax.swing.JMenu jMMaterias;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuMaterias;
    // End of variables declaration//GEN-END:variables
}
