package Vistas;

import entidades.Alumno;
import java.time.LocalDate;
import java.time.ZoneId;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class viewFormularioAlumno extends javax.swing.JInternalFrame {

    public viewFormularioAlumno() {
        super("Buscar Alumno");
        initComponents();
        LocalDate fecha=LocalDate.now();
        fecha=fecha.minusYears(18);
        jDCNacimiento.setMaxSelectableDate(Date.valueOf(fecha));
        fecha=fecha.minusYears(82);
        jDCNacimiento.setMinSelectableDate(Date.valueOf(fecha));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botones = new javax.swing.ButtonGroup();
        BotonesPrincipal = new javax.swing.ButtonGroup();
        jRBID = new javax.swing.JRadioButton();
        jRBDNI = new javax.swing.JRadioButton();
        jTDNI = new javax.swing.JTextField();
        jTNombre = new javax.swing.JTextField();
        jTID = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jLNombre = new javax.swing.JLabel();
        jTApellido = new javax.swing.JTextField();
        jLApellido = new javax.swing.JLabel();
        jLNacimiento = new javax.swing.JLabel();
        jBEliminar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jDCNacimiento = new com.toedter.calendar.JDateChooser();
        jRBInscribir = new javax.swing.JRadioButton();
        jRBBuscar = new javax.swing.JRadioButton();
        jBInscribir = new javax.swing.JButton();
        jCBModificar = new javax.swing.JCheckBox();

        Botones.add(jRBID);
        jRBID.setText("ID");
        jRBID.setEnabled(false);
        jRBID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBIDActionPerformed(evt);
            }
        });

        Botones.add(jRBDNI);
        jRBDNI.setText("DNI");
        jRBDNI.setEnabled(false);
        jRBDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBDNIActionPerformed(evt);
            }
        });

        jTDNI.setEditable(false);
        jTDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTDNIKeyTyped(evt);
            }
        });

        jTNombre.setEditable(false);
        jTNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNombreKeyTyped(evt);
            }
        });

        jTID.setEditable(false);
        jTID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTIDKeyTyped(evt);
            }
        });

        jBBuscar.setText("Buscar");
        jBBuscar.setEnabled(false);
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jBLimpiar.setText("Limpiar");
        jBLimpiar.setEnabled(false);
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        jLNombre.setText("Nombre");

        jTApellido.setEditable(false);
        jTApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTApellidoKeyTyped(evt);
            }
        });

        jLApellido.setText("Apellido");

        jLNacimiento.setText("Nacimiento");

        jBEliminar.setText("Eliminar");
        jBEliminar.setEnabled(false);
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBModificar.setText("Modificar");
        jBModificar.setEnabled(false);
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jDCNacimiento.setEnabled(false);

        BotonesPrincipal.add(jRBInscribir);
        jRBInscribir.setText("Inscribir");
        jRBInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBInscribirActionPerformed(evt);
            }
        });

        BotonesPrincipal.add(jRBBuscar);
        jRBBuscar.setText("Buscar");
        jRBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBBuscarActionPerformed(evt);
            }
        });

        jBInscribir.setText("Inscribir");
        jBInscribir.setEnabled(false);
        jBInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInscribirActionPerformed(evt);
            }
        });

        jCBModificar.setText("Modificar");
        jCBModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCBModificarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jRBInscribir)
                                .addGap(53, 53, 53)
                                .addComponent(jRBBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRBDNI)
                                    .addComponent(jRBID)
                                    .addComponent(jLNombre)
                                    .addComponent(jLApellido)
                                    .addComponent(jLNacimiento))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jTDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jTID, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jTApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jDCNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addComponent(jBInscribir)
                        .addGap(18, 18, 18)
                        .addComponent(jBModificar)
                        .addGap(18, 18, 18)
                        .addComponent(jBEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(jBBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(jBLimpiar)))
                .addGap(18, 18, 18)
                .addComponent(jBSalir)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jCBModificar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBInscribir)
                    .addComponent(jRBBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRBID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jTDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jRBDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDCNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCBModificar)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalir)
                    .addComponent(jBBuscar)
                    .addComponent(jBLimpiar)
                    .addComponent(jBEliminar)
                    .addComponent(jBModificar)
                    .addComponent(jBInscribir))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        Limpiar();
    }//GEN-LAST:event_jBLimpiarActionPerformed
    ///------------------RADIO BUTTON ID-----------------------
    private void jRBIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBIDActionPerformed
        jTID.setEditable(true);
        jTDNI.setEditable(false);
        jBBuscar.setEnabled(true);
        jCBModificar.setEnabled(false);
        jBLimpiar.setEnabled(true);
        Limpiar();
    }//GEN-LAST:event_jRBIDActionPerformed
    ///-------------------RADIO BUTTON DNI-----------------------
    private void jRBDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBDNIActionPerformed
        jTID.setEditable(false);
        jTDNI.setEditable(true);
        jBBuscar.setEnabled(true);
        jCBModificar.setEnabled(false);
        jBLimpiar.setEnabled(true);
        Limpiar();
    }//GEN-LAST:event_jRBDNIActionPerformed

    ///--------------BOTON BUSCAR--------------
    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        boolean msj=false;
        verificarSelector();
        if(jRBID.isSelected()){
            msj=verificarCampos(jTID);
            if(!msj){
                viewUniversidad.alum=viewUniversidad.alumD.buscarAlumno(Integer.parseInt(jTID.getText()));
            }
        }else if(jRBDNI.isSelected()){
            msj=verificarCampos(jTDNI);
            if(!msj){
                viewUniversidad.alum=viewUniversidad.alumD.buscarAlumnoPorDNI(Integer.parseInt(jTDNI.getText()));
            }
        }
        if(viewUniversidad.alum!=null && !msj){
            jBEliminar.setEnabled(true);
            jCBModificar.setEnabled(true);
            jTID.setText(viewUniversidad.alum.getIdAlumno()+"");
            jTDNI.setText(viewUniversidad.alum.getDni()+"");
            jTApellido.setText(viewUniversidad.alum.getApellido());
            jTNombre.setText(viewUniversidad.alum.getNombre());
            jDCNacimiento.setDate(Date.valueOf(viewUniversidad.alum.getFechaNacimiento()));
        }else if((jRBID.isSelected()||jRBDNI.isSelected())&&!msj){
            JOptionPane.showMessageDialog(null, "Alumno no encontrado");
            jCBModificar.setEnabled(false);
            Limpiar();
        }
        viewUniversidad.alum=null;
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jTIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTIDKeyTyped
        if(jTID.isEditable()){
            verificarSoloNumeros(evt,jTID);
        }
    }//GEN-LAST:event_jTIDKeyTyped

    ///--------------BOTON ELIMINAR--------------
    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        verificarSelector();
        if(jRBID.isSelected()){
            eliminar();
        }else if(jRBDNI.isSelected()){
            eliminar();
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jTDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDNIKeyTyped
        if(jTDNI.isEditable()){
            verificarSoloNumeros(evt,jTDNI);
        }
    }//GEN-LAST:event_jTDNIKeyTyped
    ///---------------------RADIO BUTTON BUSCAR---------------------
    private void jRBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBBuscarActionPerformed
        jRBID.setEnabled(true);
        jRBDNI.setEnabled(true);
        jTID.setEditable(false);
        jTDNI.setEditable(false);
        jDCNacimiento.setEnabled(false);
        jTNombre.setEditable(false);
        jTApellido.setEditable(false);
        jCBModificar.setEnabled(false);
        jBModificar.setEnabled(false);
        jBEliminar.setEnabled(false);
        jBBuscar.setEnabled(false);
        jBInscribir.setEnabled(false);
        Limpiar();
    }//GEN-LAST:event_jRBBuscarActionPerformed
    ///--------------------RADIO BUTTON INSCRIBIR--------------------
    private void jRBInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBInscribirActionPerformed
        jRBID.setEnabled(false);
        jRBDNI.setEnabled(false);
        jTID.setEditable(false);
        jTDNI.setEditable(true);
        jDCNacimiento.setEnabled(true);
        jTNombre.setEditable(true);
        jTApellido.setEditable(true);
        jCBModificar.setEnabled(false);
        jBModificar.setEnabled(false);
        jBEliminar.setEnabled(false);
        jBBuscar.setEnabled(false);
        jBInscribir.setEnabled(true);
        jBLimpiar.setEnabled(true);
        Botones.clearSelection();
        jDCNacimiento.getDateEditor().setEnabled(false);
        Limpiar();
    }//GEN-LAST:event_jRBInscribirActionPerformed
    ///------------------BOTON INSCRIBIR-----------------------------
    private void jBInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInscribirActionPerformed
        boolean msj=false;
        if(!msj){msj=verificarCampos(jTDNI);}
        if(!msj){msj=verificarCampos(jTNombre);}
        if(!msj){msj=verificarCampos(jTApellido);}
        if(!msj){
             if(jDCNacimiento.getDate()==null){
                msj=true;
                JOptionPane.showMessageDialog(null, "Completar Fecha");
                jDCNacimiento.requestFocus();
            }
        }
        if(!msj){
            viewUniversidad.alum=new Alumno(Integer.parseInt(jTDNI.getText()),jTNombre.getText(),jTApellido.getText(),jDCNacimiento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate(),true);
            viewUniversidad.alumD.guardarAlumno(viewUniversidad.alum);
            viewUniversidad.alum=null;
            Limpiar();
        }
    }//GEN-LAST:event_jBInscribirActionPerformed

   ///------------------BOTON MODIFICAR-----------------------------
    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        boolean msj=false;
        if(!msj){msj=verificarCampos(jTDNI);}
        if(!msj){msj=verificarCampos(jTNombre);}
        if(!msj){msj=verificarCampos(jTApellido);}
        if(!msj){
            if(jDCNacimiento.getDate()==null){
                msj=true;
                JOptionPane.showMessageDialog(null, "Completar Fecha");
                jDCNacimiento.requestFocus();
            }
        }
        if(!msj){
            viewUniversidad.alum=new Alumno(Integer.parseInt(jTID.getText()),Integer.parseInt(jTDNI.getText()),jTNombre.getText(),jTApellido.getText(),jDCNacimiento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate(),true);
            viewUniversidad.alumD.modificarAlumno(viewUniversidad.alum);
            viewUniversidad.alum=null;
            Limpiar();
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jCBModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBModificarMouseClicked
        modificar();
    }//GEN-LAST:event_jCBModificarMouseClicked

    private void jTNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNombreKeyTyped
        if(jTNombre.isEditable()){
            verificar(evt,jTNombre);
        }
    }//GEN-LAST:event_jTNombreKeyTyped

    private void jTApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTApellidoKeyTyped
        if(jTApellido.isEditable()){
            verificar(evt,jTApellido);
        }
    }//GEN-LAST:event_jTApellidoKeyTyped

    ///---------VERIFICAR CAMPO TEXTO REUTILIZAR CODIGO---------
    private void verificar(java.awt.event.KeyEvent evt,javax.swing.JTextField tx){
        if((evt.getKeyChar()<65||evt.getKeyChar()>90)&&(evt.getKeyChar()<97||evt.getKeyChar()>122)&&evt.getKeyChar()!=8&&evt.getKeyChar()!=32){
            JOptionPane.showMessageDialog(this, "Igresar solo letras","Advertencia",JOptionPane.WARNING_MESSAGE);
            evt.consume();
            tx.requestFocus();
        }
    }
    
    private void modificar(){
        if(jCBModificar.isSelected()){
            jRBID.setEnabled(false);
            jRBDNI.setEnabled(false);
            jTID.setEditable(false);
            jTDNI.setEditable(true);
            jDCNacimiento.setEnabled(true);
            jTNombre.setEditable(true);
            jTApellido.setEditable(true);
            jBModificar.setEnabled(true);
            jBEliminar.setEnabled(false);
            jBBuscar.setEnabled(false);
            jDCNacimiento.getDateEditor().setEnabled(false);
        }else{
            jRBID.setEnabled(true);
            jRBDNI.setEnabled(true);
            if(jRBID.isSelected()){
                jTID.setEditable(true);
                jTDNI.setEditable(false);
            }else{
                jTID.setEditable(false);
                jTDNI.setEditable(true);
            }
            jDCNacimiento.setEnabled(false);
            jTNombre.setEditable(false);
            jTApellido.setEditable(false);
            jBModificar.setEnabled(false);
            jBEliminar.setEnabled(true);
            jBBuscar.setEnabled(true);
        }
    }
    
    private void eliminar(){
        if(!verificarCampos(jTID)){
            viewUniversidad.alumD.eliminarAlumno(Integer.parseInt(jTID.getText()));
            Limpiar();
        }
    }
    
    private void verificarSelector(){
        if(!jRBID.isSelected()&&!jRBDNI.isSelected()){
            JOptionPane.showMessageDialog(null, "Elija una opcion");
        }
    }
    
    private boolean verificarCampos(javax.swing.JTextField tx){
        if(tx.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Completar Campo");
            tx.requestFocus();
            return true;
        }else{return false;}
    }
    
    private void Limpiar(){
        jTID.setText("");
        jTDNI.setText("");
        jTNombre.setText("");
        jTApellido.setText("");
        jDCNacimiento.setCalendar(null);
        jBEliminar.setEnabled(false);
        jCBModificar.setEnabled(false);
    }

    private void verificarSoloNumeros(java.awt.event.KeyEvent evt,javax.swing.JTextField tx){
        if((evt.getKeyChar()<48||evt.getKeyChar()>57)&&evt.getKeyChar()!=8){
            JOptionPane.showMessageDialog(this, "Igresar solo numeros","Advertencia",JOptionPane.WARNING_MESSAGE);
            evt.consume();
            tx.requestFocus();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Botones;
    private javax.swing.ButtonGroup BotonesPrincipal;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBInscribir;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JCheckBox jCBModificar;
    private com.toedter.calendar.JDateChooser jDCNacimiento;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLNacimiento;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JRadioButton jRBBuscar;
    private javax.swing.JRadioButton jRBDNI;
    private javax.swing.JRadioButton jRBID;
    private javax.swing.JRadioButton jRBInscribir;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTDNI;
    private javax.swing.JTextField jTID;
    private javax.swing.JTextField jTNombre;
    // End of variables declaration//GEN-END:variables
}
