/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import entidades.Materia;
import javax.swing.JOptionPane;

/**
 *
 * @author 54265
 */
public class viewFormularioMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewMaterias
     */
    public viewFormularioMateria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botones = new javax.swing.ButtonGroup();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        BotonesBuscar = new javax.swing.ButtonGroup();
        jLAño = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jTFNombre = new javax.swing.JTextField();
        jTFAño = new javax.swing.JTextField();
        jBCargar = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jBCerrar = new javax.swing.JButton();
        jRBCargar = new javax.swing.JRadioButton();
        jRBBuscar = new javax.swing.JRadioButton();
        jBBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jRBNombre = new javax.swing.JRadioButton();
        jRBCodigo = new javax.swing.JRadioButton();
        jBModificar = new javax.swing.JButton();
        jCBModificar = new javax.swing.JCheckBox();

        jLAño.setFont(new java.awt.Font("HP Simplified Jpan", 0, 15)); // NOI18N
        jLAño.setText("Año");

        jTFCodigo.setEditable(false);
        jTFCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCodigoKeyTyped(evt);
            }
        });

        jTFNombre.setEditable(false);
        jTFNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFNombreKeyTyped(evt);
            }
        });

        jTFAño.setEditable(false);
        jTFAño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFAñoKeyTyped(evt);
            }
        });

        jBCargar.setText("Cargar");
        jBCargar.setEnabled(false);
        jBCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCargarActionPerformed(evt);
            }
        });

        jBLimpiar.setText("Limpiar");
        jBLimpiar.setEnabled(false);
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        jBCerrar.setText("Cerrar");
        jBCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarActionPerformed(evt);
            }
        });

        Botones.add(jRBCargar);
        jRBCargar.setText("Cargar");
        jRBCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCargarActionPerformed(evt);
            }
        });

        Botones.add(jRBBuscar);
        jRBBuscar.setText("Buscar");
        jRBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBBuscarActionPerformed(evt);
            }
        });

        jBBuscar.setText("Buscar");
        jBBuscar.setEnabled(false);
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        BotonesBuscar.add(jRBNombre);
        jRBNombre.setText("Nombre");
        jRBNombre.setEnabled(false);
        jRBNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBNombreActionPerformed(evt);
            }
        });

        BotonesBuscar.add(jRBCodigo);
        jRBCodigo.setText("Codigo");
        jRBCodigo.setEnabled(false);
        jRBCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCodigoActionPerformed(evt);
            }
        });

        jBModificar.setText("Modificar");
        jBModificar.setEnabled(false);

        jCBModificar.setText("Modificar");
        jCBModificar.setEnabled(false);
        jCBModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCBModificarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jRBCargar)
                                .addGap(41, 41, 41)
                                .addComponent(jRBBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRBNombre)
                                    .addComponent(jRBCodigo, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCBModificar)
                                    .addComponent(jLAño))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFAño, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addComponent(jBModificar)
                .addGap(18, 18, 18)
                .addComponent(jBBuscar)
                .addGap(18, 18, 18)
                .addComponent(jBCargar)
                .addGap(18, 18, 18)
                .addComponent(jBLimpiar)
                .addGap(18, 18, 18)
                .addComponent(jBCerrar)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBBuscar)
                    .addComponent(jRBCargar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jRBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAño)
                    .addComponent(jTFAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCargar)
                    .addComponent(jBLimpiar)
                    .addComponent(jBCerrar)
                    .addComponent(jBBuscar)
                    .addComponent(jBModificar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ///---------------------BOTON CERRAR---------------------
    private void jBCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCerrarActionPerformed
    ///--------------------BOTON LIMPIAR---------------------
    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
       Limpiar();
    }//GEN-LAST:event_jBLimpiarActionPerformed
    ///-------------------BOTON CARGAR---------------------
    private void jBCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCargarActionPerformed
        boolean rep=false;
        if(!rep){rep=verificarCampos(jTFNombre);}
        if(!rep){rep=verificarCampos(jTFAño);}
        if(!rep){
            viewUniversidad.mat=new Materia(jTFNombre.getText(),Integer.parseInt(jTFAño.getText()),true);
            viewUniversidad.matD.guardarMateria(viewUniversidad.mat);
        }
    }//GEN-LAST:event_jBCargarActionPerformed
    ///--------------------RADIO BUTTON CARGAR MATERIA-------------------------------
    private void jRBCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCargarActionPerformed
        Limpiar();
        BotonesBuscar.clearSelection();
        jTFNombre.setEditable(true);
        jTFCodigo.setEditable(false);
        jTFAño.setEditable(true);
        jBBuscar.setEnabled(false);
        jBCargar.setEnabled(true);
        jBLimpiar.setEnabled(true);
        jRBCodigo.setEnabled(false);
        jRBNombre.setEnabled(false);
        jCBModificar.setEnabled(false);
        jCBModificar.setSelected(false);
        jBModificar.setEnabled(false);
    }//GEN-LAST:event_jRBCargarActionPerformed
    ///--------------------RADIO BUTTON BUSCAR MATERIA----------------------------
    private void jRBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBBuscarActionPerformed
        Limpiar();
        jTFNombre.setEditable(false);
        jTFAño.setEditable(false);
        jTFCodigo.setEditable(false);
        jBCargar.setEnabled(false);
        jBLimpiar.setEnabled(false);
        jRBCodigo.setEnabled(true);
        jRBNombre.setEnabled(true);
        jCBModificar.setEnabled(false);
    }//GEN-LAST:event_jRBBuscarActionPerformed
    ///------------------BOTON BUSCAR----------------------
    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        if(jRBCodigo.isSelected()){
            viewUniversidad.mat=viewUniversidad.matD.buscarMateriaID(Integer.parseInt(jTFCodigo.getText()));
            if(viewUniversidad.mat!=null){
                jTFNombre.setText(viewUniversidad.mat.getNombre());
                jTFAño.setText(String.valueOf(viewUniversidad.mat.getAño()));
                jCBModificar.setEnabled(true);
                viewUniversidad.mat=null;
            }else{
                Limpiar();
                JOptionPane.showMessageDialog(null, "Materia no encontrada");
            }
        }else{
            viewUniversidad.mat=viewUniversidad.matD.buscarMateriaNombre(jTFNombre.getText());
            if(viewUniversidad.mat!=null){
                jTFCodigo.setText(String.valueOf(viewUniversidad.mat.getIdMateria()));
                jTFAño.setText(String.valueOf(viewUniversidad.mat.getAño()));
                jCBModificar.setEnabled(true);
                viewUniversidad.mat=null;
            }else{
                Limpiar();
                JOptionPane.showMessageDialog(null, "Materia no encontrada");
            }
        }
    }//GEN-LAST:event_jBBuscarActionPerformed
    ///-----------------VERIFICAR SOLO NUMEROS EN JTEXT CODIGO--------------------
    private void jTFCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCodigoKeyTyped
        if(jTFCodigo.isEditable()){
            if((evt.getKeyChar()<48||evt.getKeyChar()>57)&&evt.getKeyChar()!=8){
                JOptionPane.showMessageDialog(this, "Igresar solo numeros","Advertencia",JOptionPane.WARNING_MESSAGE);
                evt.consume();
                jTFCodigo.requestFocus();
            }
        }
    }//GEN-LAST:event_jTFCodigoKeyTyped
    ///-----------------RADIO BUTTON CODIGO--------------------------
    private void jRBCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCodigoActionPerformed
        Limpiar();
        jTFCodigo.setEditable(true);
        jTFNombre.setEditable(false);
        jTFAño.setEditable(false);
        jBBuscar.setEnabled(true);
        jBLimpiar.setEnabled(true);
        jCBModificar.setEnabled(false);
    }//GEN-LAST:event_jRBCodigoActionPerformed
    ///----------------RADIO BUTTON CODIGO------------------------
    private void jRBNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBNombreActionPerformed
        Limpiar();
        jTFCodigo.setEditable(false);
        jTFNombre.setEditable(true);
        jTFAño.setEditable(false);
        jBBuscar.setEnabled(true);
        jBLimpiar.setEnabled(true);
        jCBModificar.setEnabled(false);
    }//GEN-LAST:event_jRBNombreActionPerformed
    ///--------------------CHECK MODIFICAR-------------------------
    private void jCBModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBModificarMouseClicked
        modificar();
    }//GEN-LAST:event_jCBModificarMouseClicked

    private void jTFAñoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAñoKeyTyped
        if(jTFAño.isEditable()){
            if((evt.getKeyChar()<48||evt.getKeyChar()>57)&&evt.getKeyChar()!=8){
                JOptionPane.showMessageDialog(this, "Igresar solo numeros","Advertencia",JOptionPane.WARNING_MESSAGE);
                evt.consume();
                jTFAño.requestFocus();
            }
        }
    }//GEN-LAST:event_jTFAñoKeyTyped

    private void jTFNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNombreKeyTyped
        if(jTFNombre.isEditable()){
            if((evt.getKeyChar()<65||evt.getKeyChar()>90)&&(evt.getKeyChar()<97||evt.getKeyChar()>122)&&evt.getKeyChar()!=8&&evt.getKeyChar()!=32){
                JOptionPane.showMessageDialog(this, "Igresar solo letras","Advertencia",JOptionPane.WARNING_MESSAGE);
                evt.consume();
                jTFNombre.requestFocus();
            }
        }
    }//GEN-LAST:event_jTFNombreKeyTyped
    
    private boolean verificarCampos(javax.swing.JTextField tx){
        if(tx.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Completar Campo");
            tx.requestFocus();
            return true;
        }else{return false;}
    }
    
    private void modificar(){
        if(jCBModificar.isSelected()){
            jBModificar.setEnabled(true);
            jTFNombre.setEditable(true);
            jTFAño.setEditable(true);
            jTFCodigo.setEditable(false);
            jBLimpiar.setEnabled(false);
            jBBuscar.setEnabled(false);
            jRBNombre.setEnabled(false);
            jRBCodigo.setEnabled(false);
        }else{
            jRBNombre.setEnabled(true);
            jRBCodigo.setEnabled(true);
            if(jRBCodigo.isSelected()){
                jTFNombre.setEditable(false);
                jTFCodigo.setEditable(true);
            }else{
                jTFNombre.setEditable(true);
                jTFCodigo.setEditable(false);
            }
            jBModificar.setEnabled(false);
            jTFAño.setEditable(false);
            jBLimpiar.setEnabled(true);
            jBBuscar.setEnabled(true);
            
        }
    }
    
    ///-----------LIMPIAR----------
    private void Limpiar(){
        jTFNombre.setText("");
        jTFCodigo.setText("");
        jTFAño.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Botones;
    private javax.swing.ButtonGroup BotonesBuscar;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCargar;
    private javax.swing.JButton jBCerrar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JCheckBox jCBModificar;
    private javax.swing.JLabel jLAño;
    private javax.swing.JRadioButton jRBBuscar;
    private javax.swing.JRadioButton jRBCargar;
    private javax.swing.JRadioButton jRBCodigo;
    private javax.swing.JRadioButton jRBNombre;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTFAño;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFNombre;
    // End of variables declaration//GEN-END:variables
}
