package Vistas;

import entidades.Alumno;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class viewAlumnos extends javax.swing.JInternalFrame {
    public viewAlumnos() {
        super("ALUMNOS");
        initComponents();
        cargaAlumnos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botones = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDatos = new javax.swing.JTable();
        jBSalir = new javax.swing.JButton();
        jBAnularInscripcion = new javax.swing.JButton();
        jRBAlta = new javax.swing.JRadioButton();
        jRBBaja = new javax.swing.JRadioButton();
        jBInscribir = new javax.swing.JButton();

        jTDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTDatos.setShowGrid(false);
        jScrollPane1.setViewportView(jTDatos);

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jBAnularInscripcion.setText("Anular Inscripcion");
        jBAnularInscripcion.setEnabled(false);
        jBAnularInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnularInscripcionActionPerformed(evt);
            }
        });

        Botones.add(jRBAlta);
        jRBAlta.setText("Inscriptos");
        jRBAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBAltaActionPerformed(evt);
            }
        });

        Botones.add(jRBBaja);
        jRBBaja.setText("No Inscriptos");
        jRBBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBBajaActionPerformed(evt);
            }
        });

        jBInscribir.setText("Inscribir");
        jBInscribir.setEnabled(false);
        jBInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInscribirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jBAnularInscripcion)
                        .addGap(33, 33, 33)
                        .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jRBAlta)
                .addGap(41, 41, 41)
                .addComponent(jRBBaja)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBAlta)
                    .addComponent(jRBBaja))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalir)
                    .addComponent(jBAnularInscripcion)
                    .addComponent(jBInscribir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed
    ///--------------------BOTON ANULAR INSCRIPCION-------------------------
    private void jBAnularInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnularInscripcionActionPerformed
        DefaultTableModel model=(DefaultTableModel) jTDatos.getModel();
        int[] selec=jTDatos.getSelectedRows();
        Object[] id=new Object[selec.length];
        for (int i = 0; i < selec.length; i++) {
            id[i]=(String) model.getValueAt(selec[i], 0);
        }
        if(id.length>0){
            for (int i = 0; i < id.length; i++) {
                viewUniversidad.alumD.eliminarAlumno(Integer.parseInt((String) id[i]));
            }
            cargaAlumnos();
        }
    }//GEN-LAST:event_jBAnularInscripcionActionPerformed
    ///-----------------RADIO BUTTON INSCRIPCION----------------------------
    private void jRBAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBAltaActionPerformed
        jBAnularInscripcion.setEnabled(true);
        jBInscribir.setEnabled(false);
        cargaAlumnos();
    }//GEN-LAST:event_jRBAltaActionPerformed
    ///-----------------RADIO BUTTON ANULAR INSCRIPCION---------------------------
    private void jRBBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBBajaActionPerformed
        jBInscribir.setEnabled(true);
        jBAnularInscripcion.setEnabled(false);
        cargaAlumnos();
    }//GEN-LAST:event_jRBBajaActionPerformed
    ///-----------------BOTON INSCRIPCION---------------------------
    private void jBInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInscribirActionPerformed
        DefaultTableModel model=(DefaultTableModel) jTDatos.getModel();
        int[] selec=jTDatos.getSelectedRows();
        Object[] id=new Object[selec.length];
        for (int i = 0; i < selec.length; i++) {
            id[i]=(String) model.getValueAt(selec[i], 0);
        }
        if(id.length>0){
            for (int i = 0; i < id.length; i++) {
                viewUniversidad.alumD.altaAlumno(Integer.parseInt((String) id[i]));
            }
            cargaAlumnos();
        }
    }//GEN-LAST:event_jBInscribirActionPerformed

    private void cargaAlumnos(){
        if(jRBAlta.isSelected()){
            String colum[]={"ID","Apellido","Nombre","DNI","Fecha Nacimiento"};
            viewUniversidad.alumnos=viewUniversidad.alumD.alumnosInscriptos();
            String datos[][]=new String[viewUniversidad.alumnos.size()][5];
            int i=0;
            for (Alumno alum : viewUniversidad.alumnos) {
                datos[i][0]= alum.getIdAlumno()+"";
                datos[i][1]=alum.getApellido();
                datos[i][2]=alum.getNombre();
                datos[i][3]=alum.getDni()+"";
                datos[i][4]=alum.getFechaNacimiento().getDayOfMonth()+"/"+alum.getFechaNacimiento().getMonth().getValue()+"/"+alum.getFechaNacimiento().getYear();
                i++;
                alum=null;
            }
            jTDatos.setModel(new DefaultTableModel(datos,colum));
            viewUniversidad.alumnos=null;
        }else if(jRBBaja.isSelected()){
            String colum[]={"ID","Apellido","Nombre","DNI","Fecha Nacimiento"};
            viewUniversidad.alumnos=viewUniversidad.alumD.alumnosBaja();
            String datos[][]=new String[viewUniversidad.alumnos.size()][5];
            int i=0;
            for (Alumno alum : viewUniversidad.alumnos) {
                datos[i][0]= alum.getIdAlumno()+"";
                datos[i][1]=alum.getApellido();
                datos[i][2]=alum.getNombre();
                datos[i][3]=alum.getDni()+"";
                datos[i][4]=alum.getFechaNacimiento().getDayOfMonth()+"/"+alum.getFechaNacimiento().getMonth().getValue()+"/"+alum.getFechaNacimiento().getYear();
                i++;
                alum=null;
            }
            jTDatos.setModel(new DefaultTableModel(datos,colum));
            viewUniversidad.alumnos=null;
        }else{
            String colum[]={"ID","Apellido","Nombre","DNI","Fecha Nacimiento"};
            jTDatos.setModel(new DefaultTableModel(null,colum));
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Botones;
    private javax.swing.JButton jBAnularInscripcion;
    private javax.swing.JButton jBInscribir;
    private javax.swing.JButton jBSalir;
    private javax.swing.JRadioButton jRBAlta;
    private javax.swing.JRadioButton jRBBaja;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTDatos;
    // End of variables declaration//GEN-END:variables
}
