package Vistas;

import entidades.Materia;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class viewMaterias extends javax.swing.JInternalFrame {
    public viewMaterias() {
        super("MATERIAS");
        initComponents();
        cargaMaterias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botones = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDatos = new javax.swing.JTable();
        jBSalir = new javax.swing.JButton();
        jBAnularInscripcion = new javax.swing.JButton();
        jRBInscriptas = new javax.swing.JRadioButton();
        jRBNoInscriptas = new javax.swing.JRadioButton();
        jBInscribir = new javax.swing.JButton();

        jTDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTDatos.setShowGrid(false);
        jScrollPane1.setViewportView(jTDatos);

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jBAnularInscripcion.setText("Anular Inscripcion");
        jBAnularInscripcion.setEnabled(false);
        jBAnularInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnularInscripcionActionPerformed(evt);
            }
        });

        Botones.add(jRBInscriptas);
        jRBInscriptas.setText("Inscriptas");
        jRBInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBInscriptasActionPerformed(evt);
            }
        });

        Botones.add(jRBNoInscriptas);
        jRBNoInscriptas.setText("No Inscriptas");
        jRBNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBNoInscriptasActionPerformed(evt);
            }
        });

        jBInscribir.setText("Inscribir");
        jBInscribir.setEnabled(false);
        jBInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInscribirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jBAnularInscripcion)
                        .addGap(37, 37, 37)
                        .addComponent(jBSalir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRBInscriptas)
                .addGap(54, 54, 54)
                .addComponent(jRBNoInscriptas)
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBInscriptas)
                    .addComponent(jRBNoInscriptas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalir)
                    .addComponent(jBAnularInscripcion)
                    .addComponent(jBInscribir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed
    ///-------------------BOTON ANULAR INSCRIPCION----------------
    private void jBAnularInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnularInscripcionActionPerformed
        DefaultTableModel model=(DefaultTableModel) jTDatos.getModel();
        int[] selec=jTDatos.getSelectedRows();
        Object[] id=new Object[selec.length];
        for (int i = 0; i < selec.length; i++) {
            id[i]=(String) model.getValueAt(selec[i], 0);
        }
        if(id.length>0){
            for (int i = 0; i < id.length; i++) {
                viewUniversidad.matD.eliminarMateria(Integer.parseInt((String) id[i]));
            }
            cargaMaterias();
        }
    }//GEN-LAST:event_jBAnularInscripcionActionPerformed
    ///------------------BOTON INSCRIBIR------------------
    private void jBInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInscribirActionPerformed
        DefaultTableModel model=(DefaultTableModel) jTDatos.getModel();
        int[] selec=jTDatos.getSelectedRows();
        Object[] id=new Object[selec.length];
        for (int i = 0; i < selec.length; i++) {
            id[i]=(String) model.getValueAt(selec[i], 0);
        }
        if(id.length>0){
            for (int i = 0; i < id.length; i++) {
                viewUniversidad.matD.altaMateria(Integer.parseInt((String) id[i]));
            }
            cargaMaterias();
        }
    }//GEN-LAST:event_jBInscribirActionPerformed
    ///-------------------RADIO BUTTON ALTA------------------------
    private void jRBInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBInscriptasActionPerformed
        jBAnularInscripcion.setEnabled(true);
        jBInscribir.setEnabled(false);
        cargaMaterias();
    }//GEN-LAST:event_jRBInscriptasActionPerformed
    ///-------------------RADIO BUTTON BAJA-----------------------
    private void jRBNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBNoInscriptasActionPerformed
        jBInscribir.setEnabled(true);
        jBAnularInscripcion.setEnabled(false);
        cargaMaterias();
    }//GEN-LAST:event_jRBNoInscriptasActionPerformed

    private void cargaMaterias(){
        if(jRBInscriptas.isSelected()){
            String colum[]={"Codigo","Nombre","Año"};
            viewUniversidad.materias=viewUniversidad.matD.listarMateriasAlta();
            String datos[][]=new String[viewUniversidad.materias.size()][3];
            int i=0;
            for (Materia mat : viewUniversidad.materias) {
                datos[i][0]= mat.getIdMateria()+"";
                datos[i][1]=mat.getNombre();
                datos[i][2]=mat.getAño()+"";
                i++;
                mat=null;
            }
            jTDatos.setModel(new DefaultTableModel(datos,colum));
            viewUniversidad.mat=null;
        }else if(jRBNoInscriptas.isSelected()){
            String colum[]={"Codigo","Nombre","Año"};
            viewUniversidad.materias=viewUniversidad.matD.listarMateriasBaja();
            String datos[][]=new String[viewUniversidad.materias.size()][3];
            int i=0;
            for (Materia mat : viewUniversidad.materias) {
                datos[i][0]= mat.getIdMateria()+"";
                datos[i][1]=mat.getNombre();
                datos[i][2]=mat.getAño()+"";
                i++;
                mat=null;
            }
            jTDatos.setModel(new DefaultTableModel(datos,colum));
            viewUniversidad.mat=null;
        }else{
            String colum[]={"Codigo","Nombre","Año"};
            jTDatos.setModel(new DefaultTableModel(null,colum));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Botones;
    private javax.swing.JButton jBAnularInscripcion;
    private javax.swing.JButton jBInscribir;
    private javax.swing.JButton jBSalir;
    private javax.swing.JRadioButton jRBInscriptas;
    private javax.swing.JRadioButton jRBNoInscriptas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTDatos;
    // End of variables declaration//GEN-END:variables
}
