package Vistas;

import entidades.Alumno;
import entidades.Inscripcion;
import entidades.Materia;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class viewCargaNotas extends javax.swing.JInternalFrame {

    /**
     * Creates new form CargaNotas
     */
    public viewCargaNotas() {
        super("CARGAR NOTAS");
        initComponents();
        cargaAlumnos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCBAlumnos = new javax.swing.JComboBox<>();
        jLAlumnos = new javax.swing.JLabel();
        jCBMaterias = new javax.swing.JComboBox<>();
        jLMaterias = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLNota = new javax.swing.JLabel();
        jBSalir = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jTFNota = new javax.swing.JTextField();
        jLNotaActual = new javax.swing.JLabel();
        jTFNotaActual = new javax.swing.JTextField();

        jCBAlumnos.setEnabled(false);
        jCBAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBAlumnosActionPerformed(evt);
            }
        });

        jLAlumnos.setText("Alumnos");

        jCBMaterias.setEnabled(false);
        jCBMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBMateriasActionPerformed(evt);
            }
        });

        jLMaterias.setText("Materias");

        jLNota.setText("Nota");

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jBModificar.setText("Modificar");
        jBModificar.setEnabled(false);
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jTFNota.setEditable(false);
        jTFNota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFNotaKeyTyped(evt);
            }
        });

        jLNotaActual.setText("Nota Actual");

        jTFNotaActual.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCBMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCBAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBModificar)
                        .addGap(18, 18, 18)
                        .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLNotaActual)
                        .addGap(18, 18, 18)
                        .addComponent(jTFNotaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLNota, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTFNota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNotaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNotaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNota, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalir)
                    .addComponent(jBModificar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBAlumnosActionPerformed
        viewUniversidad.alum=(Alumno)jCBAlumnos.getSelectedItem();
        cargaMaterias(viewUniversidad.alum.getIdAlumno());
        viewUniversidad.alum=null;
    }//GEN-LAST:event_jCBAlumnosActionPerformed

    private void jCBMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBMateriasActionPerformed
        viewUniversidad.mat=(Materia) jCBMaterias.getSelectedItem();
        cargaNota(viewUniversidad.mat);
        viewUniversidad.mat=null;
    }//GEN-LAST:event_jCBMateriasActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        if(Integer.parseInt(jTFNota.getText())<=10){
            viewUniversidad.alum=(Alumno) jCBAlumnos.getSelectedItem();
            viewUniversidad.mat=(Materia) jCBMaterias.getSelectedItem();
            viewUniversidad.inscripD.actualizarNota(viewUniversidad.alum.getIdAlumno(), viewUniversidad.mat.getIdMateria(), Integer.parseInt(jTFNota.getText()));
            cargaNota(viewUniversidad.mat);
            viewUniversidad.alum=null;
            viewUniversidad.mat=null;
            jTFNota.setText("");
            JOptionPane.showMessageDialog(null, "Nota Modificada");
        }else{
            JOptionPane.showMessageDialog(null, "La nota debe ser menor o igual a 10");
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jTFNotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNotaKeyTyped
        if(jTFNota.isEditable()){
            if((evt.getKeyChar()<48||evt.getKeyChar()>57)&&evt.getKeyChar()!=8){
                JOptionPane.showMessageDialog(this, "Igresar solo numeros","Advertencia",JOptionPane.WARNING_MESSAGE);
                evt.consume();
                jTFNota.requestFocus();
            }
        }
    }//GEN-LAST:event_jTFNotaKeyTyped

    private void cargaNota(Materia mat){
        if(mat!=null){
            viewUniversidad.alum=(Alumno) jCBAlumnos.getSelectedItem();
            for (Inscripcion inscrip : viewUniversidad.inscripD.obtenerInscripcionesPorAlumno(viewUniversidad.alum.getIdAlumno())) {
                if(inscrip.getAlumno().getIdAlumno()==viewUniversidad.alum.getIdAlumno()&&inscrip.getMateria().getIdMateria()==mat.getIdMateria()){
                    jTFNotaActual.setText(inscrip.getNota()+"");
                }
            }
            viewUniversidad.alum=null;
        }
    }
    
    private void cargaAlumnos(){
        viewUniversidad.alumnos=new ArrayList();
        jCBAlumnos.removeAllItems();
        jCBAlumnos.setEnabled(false);
        for (Alumno alum : viewUniversidad.alumD.alumnosInscriptos()) {
            viewUniversidad.alumnos.add(alum);
        }
        for (Alumno alumno : viewUniversidad.alumnos) {
            jCBAlumnos.addItem(alumno);
        }
        if(jCBAlumnos.getItemCount()>0){
            jCBAlumnos.setEnabled(true);
        }
        viewUniversidad.alum=(Alumno)jCBAlumnos.getSelectedItem();
        cargaMaterias(viewUniversidad.alum.getIdAlumno());
        viewUniversidad.alum=null;
        viewUniversidad.alumnos=null;
        
    }
    
    private void cargaMaterias(int id){
        jCBMaterias.removeAllItems();
        jCBMaterias.setEnabled(false);
        for (Materia mat : viewUniversidad.inscripD.obtenerMateriasCursadas(id)) {
            jCBMaterias.addItem(mat);
        }
        if(jCBMaterias.getItemCount()>0){
            jCBMaterias.setEnabled(true);
            jTFNota.setEditable(true);
            jBModificar.setEnabled(true);
        }else{
            jTFNota.setEditable(false);
            jBModificar.setEnabled(false);
            jTFNotaActual.setText("");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<Alumno> jCBAlumnos;
    private javax.swing.JComboBox<Materia> jCBMaterias;
    private javax.swing.JLabel jLAlumnos;
    private javax.swing.JLabel jLMaterias;
    private javax.swing.JLabel jLNota;
    private javax.swing.JLabel jLNotaActual;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFNota;
    private javax.swing.JTextField jTFNotaActual;
    // End of variables declaration//GEN-END:variables
}
