/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import accesoADatos.AlumnoData;
import accesoADatos.InscripcionData;
import entidades.Alumno;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 54265
 */
public class viewFormulariodeInscripcion extends javax.swing.JInternalFrame {
 private InscripcionData inscData=new InscripcionData ();
 private AlumnoData aData=new AlumnoData();
 private DefaultTableModel modelo=new DefaultTableModel();
    /**
     * Creates new form viewCargarAlumnos
     */
    public viewFormulariodeInscripcion() {
        initComponents();
        cargarAlumnos();
        armarCabecera();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGbotones = new javax.swing.ButtonGroup();
        jLFormulariodeInscripcion = new javax.swing.JLabel();
        jLAlumno = new javax.swing.JLabel();
        jCBAlumno = new javax.swing.JComboBox<>();
        jLListadodeMaterias = new javax.swing.JLabel();
        jRBInscriptas = new javax.swing.JRadioButton();
        jRBNoInscriptas = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTTablasdeMaterias = new javax.swing.JTable();
        jBInscribir = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jBAnularInscripcion = new javax.swing.JButton();

        jLFormulariodeInscripcion.setFont(new java.awt.Font("HP Simplified Jpan", 0, 23)); // NOI18N
        jLFormulariodeInscripcion.setText("-Formulario de Inscripcion-");

        jLAlumno.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLAlumno.setText("Alumno");

        jCBAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBAlumnoActionPerformed(evt);
            }
        });

        jLListadodeMaterias.setFont(new java.awt.Font("HP Simplified Jpan", 0, 17)); // NOI18N
        jLListadodeMaterias.setText("Listado de Materias");

        bGbotones.add(jRBInscriptas);
        jRBInscriptas.setFont(new java.awt.Font("HP Simplified Jpan", 0, 11)); // NOI18N
        jRBInscriptas.setText("Inscriptas");

        bGbotones.add(jRBNoInscriptas);
        jRBNoInscriptas.setFont(new java.awt.Font("HP Simplified Jpan", 0, 11)); // NOI18N
        jRBNoInscriptas.setText("No Inscriptas");

        jTTablasdeMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTTablasdeMaterias);

        jBInscribir.setText("Inscribir");

        jBSalir.setText("Salir");

        jBAnularInscripcion.setText("Anular Inscripcion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBInscribir)
                                .addGap(74, 74, 74)
                                .addComponent(jBAnularInscripcion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBSalir))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLFormulariodeInscripcion)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLListadodeMaterias)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLAlumno)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCBAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jRBInscriptas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRBNoInscriptas)
                                .addGap(50, 50, 50)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLFormulariodeInscripcion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLAlumno))
                .addGap(19, 19, 19)
                .addComponent(jLListadodeMaterias)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBInscriptas)
                    .addComponent(jRBNoInscriptas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBInscribir)
                    .addComponent(jBSalir)
                    .addComponent(jBAnularInscripcion))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBAlumnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGbotones;
    private javax.swing.JButton jBAnularInscripcion;
    private javax.swing.JButton jBInscribir;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<Alumno> jCBAlumno;
    private javax.swing.JLabel jLAlumno;
    private javax.swing.JLabel jLFormulariodeInscripcion;
    private javax.swing.JLabel jLListadodeMaterias;
    private javax.swing.JRadioButton jRBInscriptas;
    private javax.swing.JRadioButton jRBNoInscriptas;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTTablasdeMaterias;
    // End of variables declaration//GEN-END:variables
private void cargarAlumnos() {
throw new UnsupportedOperationException("Not supported yet.");
}

    private void armarCabecera() {
        ArrayList<Object> titulos=new ArrayList<>();
titulos.add("ID");
titulos.add("Nombre");
titulos.add("Año");
}
    }


