/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import entidades.Alumno;
import entidades.Inscripcion;
import entidades.Materia;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 54265
 */
public class viewFormularioInscripcion extends javax.swing.JInternalFrame {
 private DefaultTableModel modelo=new DefaultTableModel();
    /**
     * Creates new form viewCargarAlumnos
     */
    public viewFormularioInscripcion() {
        initComponents();
        cargarAlumnos();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGbotones = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLFormulariodeInscripcion = new javax.swing.JLabel();
        jLAlumno = new javax.swing.JLabel();
        jCBAlumno = new javax.swing.JComboBox<>();
        jLListadodeMaterias = new javax.swing.JLabel();
        jRBInscriptas = new javax.swing.JRadioButton();
        jRBNoInscriptas = new javax.swing.JRadioButton();
        jBInscribir = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jBAnularInscripcion = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTTablasdeMaterias = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLFormulariodeInscripcion.setFont(new java.awt.Font("HP Simplified Jpan", 0, 23)); // NOI18N
        jLFormulariodeInscripcion.setText("-Formulario de Inscripcion-");

        jLAlumno.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLAlumno.setText("Alumno");

        jCBAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBAlumnoActionPerformed(evt);
            }
        });

        jLListadodeMaterias.setFont(new java.awt.Font("HP Simplified Jpan", 0, 17)); // NOI18N
        jLListadodeMaterias.setText("Listado de Materias");

        bGbotones.add(jRBInscriptas);
        jRBInscriptas.setFont(new java.awt.Font("HP Simplified Jpan", 0, 11)); // NOI18N
        jRBInscriptas.setText("Inscriptas");
        jRBInscriptas.setEnabled(false);
        jRBInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBInscriptasActionPerformed(evt);
            }
        });

        bGbotones.add(jRBNoInscriptas);
        jRBNoInscriptas.setFont(new java.awt.Font("HP Simplified Jpan", 0, 11)); // NOI18N
        jRBNoInscriptas.setText("No Inscriptas");
        jRBNoInscriptas.setEnabled(false);
        jRBNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBNoInscriptasActionPerformed(evt);
            }
        });

        jBInscribir.setText("Inscribir");
        jBInscribir.setEnabled(false);
        jBInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInscribirActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jBAnularInscripcion.setText("Anular Inscripcion");
        jBAnularInscripcion.setEnabled(false);
        jBAnularInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnularInscripcionActionPerformed(evt);
            }
        });

        jTTablasdeMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTTablasdeMaterias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jTTablasdeMaterias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLFormulariodeInscripcion)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLListadodeMaterias)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLAlumno)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCBAlumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jRBInscriptas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRBNoInscriptas)
                                .addGap(50, 50, 50))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBInscribir)
                                .addGap(74, 74, 74)
                                .addComponent(jBAnularInscripcion)
                                .addGap(108, 108, 108)
                                .addComponent(jBSalir)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLFormulariodeInscripcion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLAlumno))
                .addGap(19, 19, 19)
                .addComponent(jLListadodeMaterias)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBInscriptas)
                    .addComponent(jRBNoInscriptas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBInscribir)
                    .addComponent(jBSalir)
                    .addComponent(jBAnularInscripcion))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBAlumnoActionPerformed
        borrarFilas();
        jBAnularInscripcion.setEnabled(false);
        jBInscribir.setEnabled(false);
        bGbotones.clearSelection();
    }//GEN-LAST:event_jCBAlumnoActionPerformed

    private void jRBInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBInscriptasActionPerformed
        borrarFilas();
        jBAnularInscripcion.setEnabled(true);
        jBInscribir.setEnabled(false);
        llenarTabla();
    }//GEN-LAST:event_jRBInscriptasActionPerformed

    private void jRBNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBNoInscriptasActionPerformed
        borrarFilas();
        jBAnularInscripcion.setEnabled(false);
        jBInscribir.setEnabled(true);
        llenarTabla();
    }//GEN-LAST:event_jRBNoInscriptasActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInscribirActionPerformed
        int selec=jTTablasdeMaterias.getSelectedRow();
        if(selec!=-1){
            viewUniversidad.alum=(Alumno)jCBAlumno.getSelectedItem();
            viewUniversidad.mat=new Materia();
            viewUniversidad.mat.setIdMateria((Integer)modelo.getValueAt(selec, 0));
            viewUniversidad.inscrip=new Inscripcion(0,viewUniversidad.alum,viewUniversidad.mat);
            viewUniversidad.inscripD.guardarInscripcion(viewUniversidad.inscrip);
            viewUniversidad.mat=null;
            viewUniversidad.alum=null;
            viewUniversidad.inscrip=null;
            borrarFilas();
            llenarTabla();
        }else{
            JOptionPane.showMessageDialog(this,"Usted debe seleccionar una materia");
        }
    }//GEN-LAST:event_jBInscribirActionPerformed

    private void jBAnularInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnularInscripcionActionPerformed
        int selec=jTTablasdeMaterias.getSelectedRow();
        if(selec!=-1){
            viewUniversidad.alum=(Alumno)jCBAlumno.getSelectedItem();
            viewUniversidad.inscripD.borrarInscripcionMateriaAlumno(viewUniversidad.alum.getIdAlumno(), (Integer)modelo.getValueAt(selec, 0));
            viewUniversidad.alum=null;
            borrarFilas();
            llenarTabla();
        }else{
            JOptionPane.showMessageDialog(this,"Usted debe seleccionar una materia");
        }
    }//GEN-LAST:event_jBAnularInscripcionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGbotones;
    private javax.swing.JButton jBAnularInscripcion;
    private javax.swing.JButton jBInscribir;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<Alumno> jCBAlumno;
    private javax.swing.JLabel jLAlumno;
    private javax.swing.JLabel jLFormulariodeInscripcion;
    private javax.swing.JLabel jLListadodeMaterias;
    private javax.swing.JRadioButton jRBInscriptas;
    private javax.swing.JRadioButton jRBNoInscriptas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTTablasdeMaterias;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private void cargarAlumnos() {
        for (Alumno alum: viewUniversidad.alumD.alumnosInscriptos()) {
            jCBAlumno.addItem(alum);
        }
        if(jCBAlumno.getItemCount()>0){
            jRBInscriptas.setEnabled(true);
            jRBNoInscriptas.setEnabled(true);
        }
    }

    private void armarCabecera() {
        ArrayList<Object> titulos=new ArrayList<>();
        titulos.add("ID");
        titulos.add("Nombre");
        titulos.add("Año");
        for (Object titulo : titulos) {
            modelo.addColumn(titulo);
        }
        jTTablasdeMaterias.setModel(modelo);
    }
    
    private void borrarFilas(){
        for (int i = modelo.getRowCount()-1; i >=0; i--) {
            modelo.removeRow(i);
        }
    }

    private void llenarTabla() {
        viewUniversidad.alum=(Alumno)jCBAlumno.getSelectedItem();
        if(jRBNoInscriptas.isSelected()){
            for (Materia materia : viewUniversidad.inscripD.obtenerMateriasNoCursadas(viewUniversidad.alum.getIdAlumno())) {
                modelo.addRow(new Object[]{materia.getIdMateria(),materia.getNombre(),materia.getAño()});
            }
        }else{
            for (Materia materia : viewUniversidad.inscripD.obtenerMateriasCursadas(viewUniversidad.alum.getIdAlumno())) {
                modelo.addRow(new Object[]{materia.getIdMateria(),materia.getNombre(),materia.getAño()});
            }
        }
        jTTablasdeMaterias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        viewUniversidad.alum=null;
    }
}


