package Vistas;

import accesoADatos.AlumnoData;
import accesoADatos.InscripcionData;
import accesoADatos.MateriaData;
import entidades.Alumno;
import entidades.Inscripcion;
import entidades.Materia;
import java.util.List;

/**
 *
 * @author 54265
 */
public class viewUniversidad extends javax.swing.JFrame {
    public static InscripcionData inscripD=new InscripcionData();
    public static AlumnoData alumD=new AlumnoData();
    public static MateriaData matD=new MateriaData();
    public static Alumno alum=null;
    public static Materia mat=null;
    public static Inscripcion inscrip=null;
    public static List<Alumno> alumnos=null;
    public static List<Materia> materias=null;
    public static List<Inscripcion> inscripciones=null;
    /**
     * Creates new form InscripcionAlumnos
     */
    public viewUniversidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMMaterias = new javax.swing.JMenu();
        jMenuMaterias = new javax.swing.JMenuItem();
        jMIListaMaterias = new javax.swing.JMenuItem();
        jMAlumno = new javax.swing.JMenu();
        jMIFormularioAlumno = new javax.swing.JMenuItem();
        jMIListaAlumnos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMIInscripcion = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMCargaDeNotas = new javax.swing.JMenu();
        jMINotas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        org.jdesktop.layout.GroupLayout jEscritorioLayout = new org.jdesktop.layout.GroupLayout(jEscritorio);
        jEscritorio.setLayout(jEscritorioLayout);
        jEscritorioLayout.setHorizontalGroup(
            jEscritorioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 614, Short.MAX_VALUE)
        );
        jEscritorioLayout.setVerticalGroup(
            jEscritorioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 385, Short.MAX_VALUE)
        );

        jMMaterias.setText("Materias");

        jMenuMaterias.setText("Formulario de Materias");
        jMenuMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMateriasActionPerformed(evt);
            }
        });
        jMMaterias.add(jMenuMaterias);

        jMIListaMaterias.setText("Lista");
        jMIListaMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIListaMateriasActionPerformed(evt);
            }
        });
        jMMaterias.add(jMIListaMaterias);

        jMenuBar1.add(jMMaterias);

        jMAlumno.setText("Alumno");

        jMIFormularioAlumno.setText("Formulario Alumno");
        jMIFormularioAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFormularioAlumnoActionPerformed(evt);
            }
        });
        jMAlumno.add(jMIFormularioAlumno);

        jMIListaAlumnos.setText("Lista Alumnos");
        jMIListaAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIListaAlumnosAlumnosActionPerformed(evt);
            }
        });
        jMAlumno.add(jMIListaAlumnos);

        jMenuBar1.add(jMAlumno);

        jMenu1.setText("Inscripcion");

        jMIInscripcion.setText("Inscripcion");
        jMIInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIInscripcionActionPerformed(evt);
            }
        });
        jMenu1.add(jMIInscripcion);

        jMenuItem1.setText("Lista Inscripciones");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMCargaDeNotas.setText("Carga de Notas");

        jMINotas.setText("Notas");
        jMINotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMINotasActionPerformed(evt);
            }
        });
        jMCargaDeNotas.add(jMINotas);

        jMenuBar1.add(jMCargaDeNotas);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMateriasActionPerformed
        // TODO add your handling code here:
        jEscritorio.removeAll();
        jEscritorio.repaint();
        viewFormularioMateria cM=new viewFormularioMateria();
        cM.setVisible(true);
        jEscritorio.add(cM);
    }//GEN-LAST:event_jMenuMateriasActionPerformed

    private void jMIListaAlumnosAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIListaAlumnosAlumnosActionPerformed
        jEscritorio.removeAll();
        jEscritorio.repaint();
        viewAlumnos vAI=new viewAlumnos();
        vAI.setVisible(true);
        jEscritorio.add(vAI);
    }//GEN-LAST:event_jMIListaAlumnosAlumnosActionPerformed

    private void jMIFormularioAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFormularioAlumnoActionPerformed
        jEscritorio.removeAll();
        jEscritorio.repaint();
        viewFormularioAlumno vBA=new viewFormularioAlumno();
        vBA.setVisible(true);
        jEscritorio.add(vBA);
    }//GEN-LAST:event_jMIFormularioAlumnoActionPerformed

    private void jMIListaMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIListaMateriasActionPerformed
        jEscritorio.removeAll();
        jEscritorio.repaint();
        viewMaterias vM=new viewMaterias();
        vM.setVisible(true);
        jEscritorio.add(vM);
    }//GEN-LAST:event_jMIListaMateriasActionPerformed

    private void jMIInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIInscripcionActionPerformed
        jEscritorio.removeAll();
        jEscritorio.repaint();
        viewFormularioInscripcion vFI=new viewFormularioInscripcion();
        vFI.setVisible(true);
        jEscritorio.add(vFI);
    }//GEN-LAST:event_jMIInscripcionActionPerformed

    private void jMINotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMINotasActionPerformed
        jEscritorio.removeAll();
        jEscritorio.repaint();
        viewCargaNotas vCN=new viewCargaNotas();
        vCN.setVisible(true);
        jEscritorio.add(vCN);
    }//GEN-LAST:event_jMINotasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jEscritorio.removeAll();
        jEscritorio.repaint();
        viewInscripciones vI=new viewInscripciones();
        vI.setVisible(true);
        jEscritorio.add(vI);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewUniversidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jEscritorio;
    private javax.swing.JMenu jMAlumno;
    private javax.swing.JMenu jMCargaDeNotas;
    private javax.swing.JMenuItem jMIFormularioAlumno;
    private javax.swing.JMenuItem jMIInscripcion;
    private javax.swing.JMenuItem jMIListaAlumnos;
    private javax.swing.JMenuItem jMIListaMaterias;
    private javax.swing.JMenuItem jMINotas;
    private javax.swing.JMenu jMMaterias;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuMaterias;
    // End of variables declaration//GEN-END:variables
}
